.Dd April 27, 2003
.Dt PMKFILE 5
.Os

.Sh NAME
.Nm pmkfile
.Nd pmk specification file

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
is file containing specifications that help configuring a package build on a given platform.

.Sh SYNTAX
.Nm
can contain comments, blank lines and commands.
.Pp
A command has the following format (? character means optional field) :
.Bd -literal -offset -indent
 .<command><?(label)> {
 <body>
 }
.Ed
.Pp
The body can contain comment and definition lines.
A commented line start with a '#' character like the following :
.Bd -literal -offset -indent
# this is a comment line
.Ed
.Pp
A definition line has the following format :
.Bd -literal -offset -indent
<?blank><key name><?blank>=<?blank><key value>
.Ed
.Pp
At this point data types must be introduced :
.Bd -literal -offset -indent
word : this is a string of alphanumerical characters and underscores only.
quoted : string of characters delimited by quoted marks that can contain escaped quotes.
list : a list is a set of one or more word and quoted separated by comma and delimited by parenthesis.
A blank is one or more space and tab characters.
.Ed
.Pp
A key name will have the word type (quote type is accepted but not recommended).
The key value could be word, quoted and list relatively to the type needed for the key. 
.Pp
Example :
.Bd -literal -offset -indent
 .CHECK_INCLUDE(header_sys_param) {
 # following options use different uses of blank characters
 # key value is word type
 REQUIRED = TRUE
 # key value is list type
 DEPEND=	("dep_one", dep_two,"dep_three")
 # key value is quoted type
 INCLUDE = "sys/param.h"
 }
.Ed

.Sh SPECIFIC COMMANDS
.Pp
The following commands have no label.
.Bl -tag -width Ds
.It Cm DEFINE
This command permits to define variables.
.Pp
Arguments :
.Pp
Example :
.Bd -literal -offset -indent
 .DEFINE {
 PACKAGE=myprog
 VERSION=0.1
 }
.Ed

.It Cm TARGET
This command defines the target templates where values will be substitued.
.Pp
Arguments :
.Bd -literal -offset -indent
LIST : list of filename separated by a comma.
.Ed
.Pp
Example :
.Bd -literal -offset -indent
 .TARGET {
 LIST=Makefile.in,common.pmk
 }
.Ed

.It Cm AC_COMPAT
This command enable autoconf compatibility.
.Pp
Arguments :
.Bd -literal -offset -indent
FILENAME : autoconf config file.
.Ed
.Pp
Example :
.Bd -literal -offset -indent
 .AC_COMPAT {
 FILENAME=config.h
 }
.Ed
.El

.Sh STANDARD COMMANDS
.Pp
All these commands need a label.
.Pp
They all can have the following optional arguments :
.Bl -tag -width Ds
.It Cm REQUIRED
Specify if this test is required to achieve the configuration. If not specified it is TRUE by default.
.It Cm DEPEND
Specify check dependencies. If a dependancy is already false then the test will be false.
.El
.Pp
Some of these commands can also have the following arguments :
.Bl -tag -width Ds
.It Cm LANG
Specify the language used in the following list :
.Bd -literal -offset -indent
C
C++
.Ed
.Pp By default C is the used language.
.El
.Pp
Here the list of commands :
.Bl -tag -width Ds
.It Cm CHECK_BINARY
Check if a binary is in the path.
.Pp
Arguments :
.Bd -literal -offset -indent
FILENAME : name of the binary.
.Ed
.It Cm CHECK_INCLUDE
Check language header and optionally a function.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND, LANG.
INCLUDE : name of the header.
FUNCTION : function to check, optional.
.Ed
.It Cm CHECK_LIB
Check a library and optionally a function.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND, LANG.
LIBNAME : library name to check.
FUNCTION : function to check, optional.
.Ed
.It Cm CHECK_CONFIG
Check using a *-config tool.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND.
CFGTOOL : config tool name.
VERSION : minimal version needed, optional.
CFLAGS : variable name to store CFLAGS values, optional.
LIBS : variable name to store LIBS values, optional.
.Ed
.It Cm CHECK_PKG_CONFIG
Check a package using pkg-config.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND.
PACKAGE : package name.
VERSION : minimal version needed, optional.
CFLAGS : variable name to store CFLAGS values, optional.
LIBS : variable name to store LIBS values, optional.
.Ed
.It Cm CHECK_TYPE
Check if the given type exists.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND, LANG.
TYPE : type name.
.Ed
.El

.Sh SEE ALSO
.Xr pmk 1

.Sh AUTHOR
.An Damien Couderc

.Sh HISTORY
The idea to replace configure script was existing since a long time. 
But the projet was initiated in the begining of March 2003.
