.\" $Id$

.Dd April 27, 2003
.Dt PMKFILE 5
.Os

.Sh NAME
.Nm pmkfile
.Nd pmk specification file

.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION
.Nm
is a file containing specifications that help configuring a package build on a given platform.

.Sh DATA TYPES
.Nm
is using pseudo types like the following :
.Bl -tag -width Ds
.It Cm bool
The classical boolean type with TRUE and FALSE values.
.Pp
Examples :
.Bd -literal -offset -indent
 TRUE
 FALSE
.Ed

.It Cm identifier
An identifier is a string of alphanumerical and underscores characters.
.Pp
Examples :
.Bd -literal -offset -indent
 REQUIRED
 a_label 
 underscores_are_nice
.Ed

.It Cm quoted
This means quoted string which can contain a set of characters delimited by quotation marks.
.Pp
Examples :
.Bd -literal -offset -indent
 "simple quoted string"
 "string that contain \\"quotes\\" backslashed"
 "can also contain filenames like pmkfile.scan"
.Ed

.It Cm list
It is one or more of the previous types between brackets. Multiple objects are separated with a comma.
Blanks are currently not allowed beside commas, this means that you can find them only in a quoted string of the list.
.Pp
Examples :
.Bd -literal -offset -indent
 ("only_one_string")
 ("added a boolean",TRUE)
 (mixed_list_of,"words","and",TRUE,"quoted strings")
.Ed
.El

.Sh SYNTAX
.Nm
can contain comments, blank lines and commands.
.Pp
A command has the following format (? character means optional field) :
.Bd -literal -offset -indent
 <command><?(label)> {
 <body>
 }
.Ed
.Pp
The command and label names can be assimilated to the 'word' type (see data types).
.Pp
The body can contain comment(s) and definition line(s).
A commented line start with a '#' character like the following :
.Bd -literal -offset -indent
# this is a comment line
.Ed
.Pp
A definition line has the following format :
.Bd -literal -offset -indent
<?blank><key name><?blank>=<?blank><key value>
.Ed
.Pp
The key name is of identifier type.
.Pp
The key value type can be 'bool', 'quoted' or 'list'. The right type will depend on the key name (see further).
.Pp
Example :
.Bd -literal -offset -indent
CHECK_INCLUDE(header_sys_param) {
 # following options use different uses of blank characters
 # key value is word type
 REQUIRED = TRUE
 # key value is list type
 DEPEND=	("dep_one",dep_two,"dep_three")
 # key value is quoted type
 INCLUDE = "sys/param.h"
}
.Ed

.Sh SPECIFIC COMMANDS
.Pp
The following commands have no label.
.Bl -tag -width Ds
.It Cm DEFINE
This command permits to define variables.
.Pp
Arguments :
.Pp
Example :
.Bd -literal -offset -indent
DEFINE {
 PACKAGE="my_prog"
 VERSION="0.1"
}
.Ed

.It Cm SETTINGS
This command sets pmk parameters. 
.Pp
Arguments :
.Bd -literal -offset -indent
AC_COMPAT : type is 'quoted', enable autoconf compatibility (empty string or filename).
LANG : type is 'quoted', global default language.
TARGET : type is 'list', list of target's filenames.
.Ed
.Pp
Example :
.Bd -literal -offset -indent
SETTINGS {
 AC_COMPAT="config.h"
 LANG="C"
 TARGET=("src/file.c","src/file.h")
}
.Ed

.It Cm SWITCHES
This command is setting dependency switches (see further DEPEND definition).
.Pp
Arguments :
.Pp
Example :
.Bd -literal -offset -indent
SWITCHES {
 use_curses=TRUE
 use_gtk=FALSE
}
.Ed
.El

.Sh STANDARD COMMANDS
.Pp
All these commands need a label.
.Pp
They all can have the following optional arguments :
.Bl -tag -width Ds
.It Cm REQUIRED
Specify if this test is required to achieve the configuration. Type is 'bool'.
If not specified it is TRUE by default.
.It Cm DEPEND
Specify check dependencies. Type is 'list'. A dependency is a label or a switch name.
The value of each dependencie can be negated by adding a leading '!' sign.
If at least one of the dependencies is false then the check will be disabled.
.Pp
Example :
.Bd -literal -offset -indent
DEPEND = ("header_gtk","!header_qt")
.Ed
.El
.Pp
Some of these commands can also have the following arguments :
.Bl -tag -width Ds
.It Cm LANG
Specify the language used in the following list :
.Bd -literal -offset -indent
C
C++
.Ed
.Pp Type is 'quoted', by default \\"C\\" is the used language.
.El
.Pp
Here the list of commands :
.Bl -tag -width Ds
.It Cm CHECK_BINARY
Check if a binary is in the path.
.Pp
Arguments :
.Bd -literal -offset -indent
REQUIRED, DEPEND.
NAME : type is 'quoted', name of the binary.
VARIABLE : type is 'quoted', variable name to store the path.
.Ed
.It Cm CHECK_INCLUDE
Check language header and optionally a function.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND, LANG.
NAME : type is 'quoted', name of the header.
FUNCTION : type is 'quoted', function to check, optional.
CFLAGS : type is 'quoted', variable name to store CFLAGS values, optional.
.Ed
.It Cm CHECK_LIB
Check a library and optionally a function.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND, LANG.
NAME : type is 'quoted', name of the library to check.
FUNCTION : type is 'quoted', function to check, optional.
LIBS : type is 'quoted', variable name to store LIBS values, optional.
.Ed
.It Cm CHECK_CONFIG
Check using a *-config tool.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND.
NAME : type is 'quoted', config tool name.
VERSION : type is 'quoted', minimal version needed, optional.
CFLAGS : type is 'quoted', variable name to store CFLAGS values, optional.
LIBS : type is 'quoted', variable name to store LIBS values, optional.
VARIABLE : type is 'quoted', variable name to store the path of the config tool, optional.
.Ed
.It Cm CHECK_PKG_CONFIG
Check a package using pkg-config.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND.
NAME : type is 'quoted', package name.
VERSION : type is 'quoted', minimal version needed, optional.
CFLAGS : type is 'quoted', variable name to store CFLAGS values, optional.
LIBS : type is 'quoted', variable name to store LIBS values, optional.
.Ed
.It Cm CHECK_TYPE
Check if the given type exists.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND, LANG.
NAME : type is 'quoted', name of the type to check.
.Ed
.It Cm CHECK_VARIABLE
Check if the given variable exists and optionally it's value.
.Pp
Arguments:
.Bd -literal -offset -indent
REQUIRED, DEPEND.
NAME : type is 'quoted', name of the variable to check.
VALUE : type is 'quoted', value to check with the variable, optional.
.Ed
.El

.Sh CONDITIONAL COMMANDS
.Bl -tag -width Ds
.It Cm IF(expression)
It contains other commands that will be executed only if the given expression is true.
.Pp
Arguments :
.Pp
Example :
.Bd -literal -offset -indent
IF(header_gtk) {
	DEFINE {
		HAVE_GTK = "1"
	}
}
.Ed
.El

.Sh SEE ALSO
.Xr pmk 1

.Sh AUTHOR
.An Damien Couderc

.Sh HISTORY
The idea to replace configure script was existing since a long time. 
But the projet was initiated in the begining of March 2003.
