.\" $Id$
.
.Dd March 28, 2003
.Dt PMKSCAN 1
.Os
.
.Sh NAME
.Nm pmkscan
.Nd source scanning tool
.
.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl hlv
.Op Fl f Ar file
.Ek
.
.Sh DESCRIPTION
.Nm
is a tool which scans the sources with the intention to generate build files like
.Xr pmkfile 5
, config file template (by default config.h.pmk) and makefile template (by default Makefile.pmk).
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl f Ar file
Use the given file instead of the default script named
.Xr scanfile 5
which should be in the working directory.
.It Fl h
Display usage.
.It Fl l
Log into pmkscan log file.
.It Fl v
Display the version number.
.El
.Pp
.Sh FILES
.Bl -tag -width "pmkfile" -compact
.It Pa pmkfile
default
.Xr pmkscan 1
generated pmkfile.
.It Pa pmkscan.dat
.Xr pmkscan 1
database
.It Pa scanfile
.Xr pmkscan 1
specifications file
.El
.
.Sh SEE ALSO
.Xr pmk 1 ,
.Xr pmkfile 5
.Xr scanfile 5
.
.Sh AUTHOR
.An Damien Couderc .
