.\" $Id$

.Dd March 28, 2003
.Dt PMKSCAN 1
.Os

.Sh NAME
.Nm pmkscan
.Nd source scanning tool

.Sh SYNOPSIS
.Nm
.Bk -words
.Op Fl hmprv
.Op Ar path
.Ek

.Sh DESCRIPTION
.Nm
is a tool which scans the sources with the intention to generate a
.Xr pmkfile 5
template (named pmkfile.scan), a makefile template (named Makefile.scan)
or both.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
Display usage.
.It Fl m
Generate a Makefile template.
.It Fl p
Generate a pmkfile template.
.It Fl r
Recursive scan.
.It Fl v
Display the version number.
.El
.Pp
.Ar path
is optional as default
.Ar path
is the current working directory.
.Sh FILES
.Bl -tag -width "pmkfile.scan" -compact
.It Pa pmkfile.scan
default
.Xr pmkscan 1
resulting template
.It Pa pmkscan.dat
.Xr pmkscan 1
database
.It Pa scanfile
.Xr pmkscan 1
specifications file
.El

.Sh SEE ALSO
.Xr pmk 1 ,
.Xr pmkfile 5
.Xr scanfile 5

.Sh AUTHOR
.An Damien Couderc .
