.Dd "March 2003"
.Dt PMK 1
.Sh NAME
.Nm pmk
.Nd configuring tool
.Sh SYNOPSIS
.Nm
.Op -vh
.Op -f file
.Op options
.Sh DESCRIPTION
.Pp
.Nm
is a configuring tool which aims to help building project on different operanding systems.
.Ss Options :
.Tp
\-v
.Dl Display version.
.Tp
\-h
.Dl Display usage.
.Tp
\-f \fIfile\fR
.Dl Use \fIfile\fR instead of \fBpmkfile\fR.
.Sh FILES
.Pp
pmkfile
.Pp
pmk.conf
.Sh SEE ALSO
pmksetup(1), pmkfile(5), pmk.conf(5)
.Sh HISTORY
The idea to replace configure script was existing since a long time. But the projet was initiated in the begining of March 2003
.Sh AUTHOR
.An Damien Couderc
.Sh BUGS
You fool ?
